# Generated by Django 2.2.7 on 2020-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'User Progress Result', 'verbose_name_plural': 'Student Result'},
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Quiz Name'),
        ),
    ]
