# Generated by Django 2.2.7 on 2020-12-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20201228_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
    ]
