# Generated by Django 2.2.7 on 2020-12-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20201228_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Total_Score',
            field=models.IntegerField(verbose_name='Total Score'),
        ),
    ]
