# Generated by Django 2.2.7 on 2020-12-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20201228_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='draft',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='single_attempt',
            field=models.BooleanField(default=True, help_text='If yes, only one attempt by a user will be permitted. Non users cannot sit this exam.', verbose_name='Single Attempt'),
        ),
    ]
